Update Readme and enhance pipeline
Staffbase/yamllint-action pull request #7
Opened 2021-07-06 12:54 UTC by axdotl

- Updated README
- Make use of [goreleaser](https://goreleaser.com)
- Adjust ci-cd pipeline and publish to DockerHub

2021-07-06 14:38 UTC, kaitimmer approved these changes

2021-07-07 07:02 UTC, 0x46616c6b requested changes
Did you think about using https://github.com/goreleaser/goreleaser?

2021-07-07 07:07 UTC, 0x46616c6b requested changes
Please check also if you using a actual Go version to build the action.

2021-07-07 08:50 UTC, 0x46616c6b approved these changes

2021-07-07 08:51 UTC, merged